### ISSUE TITLE
bfoperate: bloom filters with more than one bit vectors

### ISSUE THREAD

**Issue by cumbof** [medvedevgroup/HowDeSBT#3]
I noticed that you check now whether the input bloom filters contain only one bit vector each before applying a specific logic operator with the `bfoperate` subcommand.

This totally makes sense, but I didn't get why the condition on the number of bit vectors should be `> 2` in case of the second bloom filter passed in input (`bfB`). Should it probably be fixed with `> 1` as well as you already do with the first bloom filter `bfA`?

**void BFOperateCommand::op_and()**
https://github.com/medvedevgroup/HowDeSBT/blob/aaab7329d00100d618bb3f947844443aa7800bd3/cmd_bf_operate.cc#L243-L246

**void BFOperateCommand::op_or()**
https://github.com/medvedevgroup/HowDeSBT/blob/aaab7329d00100d618bb3f947844443aa7800bd3/cmd_bf_operate.cc#L278-L281

**void BFOperateCommand::op_xor()**
https://github.com/medvedevgroup/HowDeSBT/blob/aaab7329d00100d618bb3f947844443aa7800bd3/cmd_bf_operate.cc#L313-L316

**void BFOperateCommand::op_eq()**
https://github.com/medvedevgroup/HowDeSBT/blob/aaab7329d00100d618bb3f947844443aa7800bd3/cmd_bf_operate.cc#L348-L351

**Comment by rsharris** [comment]
Man, what a stupid mistake!  I'll push a fix shortly.    Thanks!

**Comment by rsharris** [comment]
Now corrected.  Thanks again.
