### ISSUE TITLE
Building a pre-release with new features (--rrr, --unrrr, and --list in bfoperate subcommand)

### ISSUE THREAD

**Issue by cumbof** [medvedevgroup/HowDeSBT#5]
This is not really an issue. 

I'm developing a framework that makes use of HowDeSBT for building SBTs, and for most of the users it would for sure be easier to install HowDeSBT with conda.

Just wondering whether it could be possible to create a new tagged pre-release so that I could easily update the conda recipe to point to a specific tag with the last features (i.e., `--rrr`, `--unrrr`, and `--list` in `bfoperate` subcommand).

**Comment by rsharris** [comment]
Yeah, I will tag this as a release shortly.

**Comment by rsharris** [comment]
Done. It is 2.00.07.  Master is now 2.00.08.

**Comment by cumbof** [comment]
Thanks again Bob!
