### ISSUE TITLE
bfdistance: one filter vs a set of filters

### ISSUE THREAD

**Issue by cumbof** [medvedevgroup/HowDeSBT#8]
This is actually not an issue, it is more like a request to implement a new feature.

The `bfdistance` command automatically compute the pair-wise distance between all the BF files listed in `--list=<filename>`. This is great but it is not currently possible to make it parallel and speed up the whole process, which would be extremely helpful when dealing with hundred thousands of BFs. This is probably not straightforward but can be indirectly solved by thinking of another problem.

In particular, let say that I want to compute the distance between one BF only and a set of BFs. This is not currently possible, but it seems super easy to implement since `bfdistance` already takes one BF file `<filename>` and a list of BF files `--list=<filename>` in input. The idea is that it could compute the distance between `<filename>` and `--list=<filename>` whether both of them are specified in input (currently, it seems ignoring `<filename>` if `--list=<filename>` is also specified, but I may be wrong).

At this point, there would be no reason to think about a way to make it parallel since we could simply run multiple instances of `howdesbt bfdistance` with different `<filename>` but all with the same `--list=<filename>`.

**Comment by rsharris** [comment]
> (currently, it seems ignoring <filename> if --list=<filename> is also specified, but I may be wrong)

Actually, it accumulates all the filenames specified on the command line, plus any that are in a file specified by --list=<filename>.

To maintain backward compatibility, I would add another option, something like --reference=<filename>. And then compute the distance between that reference BF and any other bfs specified (whether by filename or by --list).

I'd also need to figure out whatever other commands behave the same as bfdistance and implement the same for those.

At present, I don't have a built version of the program on my machine, and when I attempted to build it I ran into a problem with access to h files for one of the libraries. So it'll be a while before I implement this.

**Comment by cumbof** [comment]
The `--reference=<filename>` solution in conjunction with `<filename>` or `--list=<filename>` would be great to have!
You would probably do the same for the `bfoperate` command.

**Comment by rsharris** [comment]
Thanks — I think `bfoperate` is the only similar command.

I'm not sure if `reference` is the best name for this option. What do you think of these alternatives: focus, base, basis, common, target, kernel, ground, center, keystone, core, object? I'm leaning toward `focus`.

**Comment by cumbof** [comment]
I agree, `focus` is probably the best one, I would go with that

**Comment by rsharris** [comment]
Added `--focus=<filename>`. Only added to `bfdistance`. I looked at `bfoperate` but decided that uses the collection of filters differently, So I didn't think `--focus=<filename>` made sense there.

I added more detail to the usage message `?bfdistance`.

**Comment by cumbof** [comment]
That’s awesome! Could you also create a new release or pre-release so that I can update the conda package as well?

**Comment by rsharris** [comment]
It's now tagged as release 2.00.15 .

As I am doing less and less with github these days, the chance that I will remember to update version numbers and do things like tag releases (or even *how* to tag a release) decreases.

**Comment by cumbof** [comment]
Thanks!
